# run alacritty using default settings for debug purposes
# alacritty --config-file /dev/null

[general]
live_config_reload = true

# [shell]
#    program = "zsh"
#    args = ["-l", "-c", "SHELL=$(which zsh); export SHELL; source $HOME/.config/shell/functions/tmux.sh; __attach_unattached_session"]

[cursor]
   blink_interval = 500
   blink_timeout = 0
   thickness      = 0.01
   style          = { blinking = "Always", shape = "Beam" }

[env]
   TERM = "alacritty"

[font]
   size        = 18
   offset      = { x = 1, y = 5 }
   bold        = { family = "SauceCodePro Nerd Font", style = "Regular" }
   bold_italic = { family = "MonaspiceRn Nerd Font", style = "Light" }
   normal      = { family = "SauceCodePro Nerd Font", style = "Regular" }
   italic      = { family = "CaskaydiaMono Nerd Font", style = "Light Italic" }

[selection]
   save_to_clipboard = true

[window]
   decorations     = "none"
   dynamic_padding = true
   opacity         = 0.7
   startup_mode    = "Maximized"
   padding         = { x = 16 }

[colors]
   cursor  = { cursor = "#ffffff", text = "#000000" }
   primary = { background = "#000000", foreground = "#d0d0d0" }

[colors.bright]
   # black   = "#d0d0d0"
   black   = "#7a7c9e"
   blue    = "#5c5cff"
   cyan    = "#0DCDCD"
   green   = "#65b588"
   magenta = "#FF00FF"
   red     = "#ff0000"
   white   = "#ffffff"
   yellow  = "#ffe330"

[colors.normal]
   black = "#000000"
   blue  = "#9bb7c4"
   cyan  = "#6097bf"
   green = "#5f9e6f"
   magenta = "#8856c4"
   red    = "#ff75a9"
   white  = "#e4e8f2"
   yellow = "#d9b26f"

[[hints.enabled]]
   regex = "(http:|https:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
   command = "xdg-open"

[hints.enabled.binding]
   key = "L"
   mods = "Alt"

[keyboard]
   bindings = [
      { action = "ResetFontSize", key = "Equals", mods = "Control" },
      { action = "IncreaseFontSize", key = "Plus", mods = "Control|Shift" },
      { action = "DecreaseFontSize", key = "Minus", mods = "Control" },
      { action = "ResetFontSize", key = "NumpadEquals", mods = "Control" },
      { action = "IncreaseFontSize", key = "NumpadAdd", mods = "Control" },
      { action = "DecreaseFontSize", key = "NumpadSubtract", mods = "Control" },

      { action = "ScrollLineUp", key = "PageUp", mods = "Shift" },
      { action = "ScrollLineUp", key = "PageUp", mods = "Shift" },
      { action = "ScrollLineUp", key = "PageUp", mods = "Shift" },
      { action = "ScrollLineUp", key = "PageUp", mods = "Shift" },
      { action = "ScrollLineDown", key = "PageDown", mods = "Shift" },
      { action = "ScrollLineDown", key = "PageDown", mods = "Shift" },
      { action = "ScrollLineDown", key = "PageDown", mods = "Shift" },
      { action = "ScrollLineDown", key = "PageDown", mods = "Shift" },

      { action = "ScrollToTop", key = "Home", mods = "Shift" },
      { action = "ScrollToBottom", key = "End", mods = "Shift" },

      { chars = "\u001B[105;5u", key = "I", mods = "Control" },
      { chars = "\u001B[13;2u", key = "Return", mods = "Shift" },
      { chars = "\u001B[13;5u", key = "Return", mods = "Control" },
      { chars = "\u001B[13;6u", key = "Return", mods = "Control|Shift" },
      { chars = "\u001B[13;4u", key = "Return", mods = "Alt|Shift" },
      { chars = "\u001B[3;2~", key = "Backspace", mods = "Shift" },
      { chars = "\u001B[27;5;127~", key = "Backspace", mods = "Control" },
      # { chars = "\u001B[127;5u", key = "Backspace", mods = "Control" },
      { chars = "\u001B[32;2u", key = "Space", mods = "Shift" },
      { chars = "\u001B\u001B[Z", key = "Tab", mods = "Alt|Shift" },
      { chars = "\u001B[Z", key = "Tab", mods = "Shift" },
      { chars = "\u001B[9;5u", key = "Tab", mods = "Control" },
      { chars = "\u001B[9;6u", key = "Tab", mods = "Control|Shift" },
      { chars = "\u001B[9;7u", key = "Tab", mods = "Control|Alt" },
      { chars = "\u001B[9;8u", key = "Tab", mods = "Control|Alt|Shift" },
      { chars = "\u0002[", key = "Escape", mods = "Control" },
      { chars = "\u001b", key = "Escape", mods = "Shift" },

      { chars = "\u001B[48;5u", key = "Key0", mods = "Control" },
      { chars = "\u001B[49;5u", key = "Key1", mods = "Control" },
      { chars = "\u001B[50;5u", key = "Key2", mods = "Control" },
      { chars = "\u001B[51;5u", key = "Key3", mods = "Control" },
      { chars = "\u001B[52;5u", key = "Key4", mods = "Control" },
      { chars = "\u001B[53;5u", key = "Key5", mods = "Control" },
      { chars = "\u001B[54;5u", key = "Key6", mods = "Control" },
      { chars = "\u001B[55;5u", key = "Key7", mods = "Control" },
      { chars = "\u001B[56;5u", key = "Key8", mods = "Control" },
      { chars = "\u001B[57;5u", key = "Key9", mods = "Control" },
   ]
