[ -f "$OUT/.config/shell/xdg.sh" ] && source "$OUT/.config/shell/xdg.sh"
[ -f "$OUT/.config/shell/variables.sh" ] && source "$OUT/.config/shell/variables.sh"

# disable bold in the ls command output
# LS_COLORS=${LS_COLORS//01;/00;}
# export LS_COLORS
# export EDITOR=nvim

export HISTFILE="${XDG_STATE_HOME}"/bash/history

# source "$OUT/.config/shell/scripts/ssh-agent.sh"

# # Show completion options on first Tab, cycle through on second Tab
# bind 'set show-all-if-ambiguous on'
# bind 'set menu-complete-display-prefix on'
# bind '"\t": menu-complete'
# bind '"\e[Z": menu-complete-backward' # Shift+Tab for reverse completion

bind -x '"\C-n":"nvim"'
bind -x '"\C-b":"br -c :open_preview"'
bind -x '"\C-n":"__nextd"'
bind -x '"\C-p":"__prevd"'

# unbind alt-number
for i in "-" {0..9}; do bind -r "\e$i"; done

# unbind ctrl-s and ctrl-q (terminal scroll lock)
stty -ixon

[ -f "$OUT/.config/shell/aliases.sh" ] && source "$OUT/.config/shell/aliases.sh"

if [ -d "$OUT/.config/shell/functions" ]; then
  for file in "$OUT/.config/shell/functions"/*.sh; do
    . "$file"
  done
fi

command -v navi >/dev/null 2>&1 && eval "$(navi widget bash)"
command -v starship >/dev/null 2>&1 && eval "$(starship init bash)"
command -v zoxide >/dev/null 2>&1 && eval "$(zoxide init --no-cmd bash)"
command -v direnv >/dev/null 2>&1 && eval "$(direnv hook bash)"

if [[ :$SHELLOPTS: =~ :(vi|emacs): ]]; then
  . "$(fzf-share)/completion.bash"
  . "$(fzf-share)/key-bindings.bash"
fi
